### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by CryptoDevving** [aditya172926/Subvid_stream#11]
Hello,
Am I able to use this in my project? 

Thanks

**Comment by aditya172926** [comment]
I am not sure I understand. What do you mean by using this in your project?

**Comment by CryptoDevving** [comment]
There is no license on the github repo and I was wondering if I could integrate it in my crypto currency project.

**Comment by aditya172926** [comment]
What is your project exactly? Can you explain more about it? And how do you plan to use my project in yours?

**Comment by aditya172926** [comment]
Also thanks for pointing out the absence of a license, I will add one soon.

**Comment by CryptoDevving** [comment]
Sometimes I like to review code or understand how another project works. This helps me understand certain features. 

No worries. I will see what you put the license as. 

Edit: you are most welcome.
