### ISSUE TITLE
Adding support for Metamask

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/Subvid_stream#12]
The whole dapp is using Celo Blockchain right now. The token used for the subscription is an ERC20 Stable coin on Celo known as cUSD.

This addresses the point of view to have a version of dapp where it is using Metamask wallet with other networks.

If this migration task is up to your skills comment down, get assigned and start working 🤘

**Comment by ocdbytes** [comment]
Assign this to me @aditya172926 and please merge the PR I created for Address -> Username mapping.

**Comment by aditya172926** [comment]
That PR has some conflict issues. Also there are some logical errors which is not allowing me to make a transaction in the website using my Celo wallet. I will keep this issue open before that is resolved.

**Comment by ocdbytes** [comment]
That PR is resolved now 🚀
@aditya172926

**Comment by aditya172926** [comment]
Yeah. Assigning this issue to you. Great work so far 🔥 @Arun89-crypto

**Comment by ocdbytes** [comment]
Thank You @aditya172926
