### ISSUE TITLE
Mapping address to Readable names

### ISSUE THREAD

**Issue by aditya172926** [aditya172926/Subvid_stream#13]
This issue is with direct implications for the [Subvid stream smart contracts issue](https://github.com/aditya172926/Subvid_stream_contracts/issues/4)

On Web3 we do have our wallet addresses which uniquely identify us. But we as humans are very used to dealing with readable names.

![image](https://user-images.githubusercontent.com/54861484/195679204-327a91e7-5e1b-4b3b-aa6c-481a5772faaf.png)

**Comment by ocdbytes** [comment]
Hello @aditya172926 ,
Please assign this issue to me.

**Comment by ocdbytes** [comment]
Username Functionality working on Remix IDE After deployment of the contract 


<img src="https://drive.google.com/uc?export=view&id=1hDp78w2ym2RPa_hoGeNRVc6ApLhbFTn-"></img>

Deploy the contract using your celo wallet so that I can test on Frontend @aditya172926

**Comment by ocdbytes** [comment]
PR created #17 
Please merge and add the hacktoberfest-accepted label

**Comment by ocdbytes** [comment]
@aditya172926 Please review the PR

**Comment by aditya172926** [comment]
Alright will look into it.

**Comment by ocdbytes** [comment]
All the changes made as expected. Merge conflicts resolved. Review the PR #17 
@aditya172926
