### ISSUE TITLE
Prettier config file missing

### ISSUE THREAD

**Issue by Rohit-Saini7** [aditya172926/Subvid_stream#15]
Nowadays everyone uses [Prettier](https://prettier.io/), An opinionated code formatter.

The issue is everyone have different global settings of prettier according to their style. but this can cause useless changes to opensource projects as many people works on same code.

So having a prettier config file inside project directory can resolve this issue.

**Comment by aditya172926** [comment]
Makes sense. It would be nice to have all files using a unified code format. @RohitSaini7
